### ISSUE TITLE
Default unit

### ISSUE THREAD

**Issue by BigFunger** [adriano-di-giovanni/expiry-js#2]
What do you think about having a way to specify a default unit?
Something along these lines:

```
var expiry = require('expiry-js');
expiry.defaultUnit('s');

var input = '300';
var duration = expiry(input);
console.log(duration.asSeconds());
```

would process the input of '300' as seconds, instead of assuming invalid input?

**Comment by adriano-di-giovanni** [comment]
Can you outline an use case, please?

**Comment by BigFunger** [comment]
I am considering using expiry-js to parse a command line argument for script timeout. In this context, the command line option makes the most sense expressed in seconds, however, we also support minutes.

If the user specifies a number without a unit expiry-js returns undefined. I added additional logic to my application to address this issue, but I thought it might be a feature that would fit well in expiry-js.

**Comment by adriano-di-giovanni** [comment]
`expiry()` also accepts a milliseconds argument of type `Number`.

``` javascript
var
  expiry = require('expiry-js');

console.log(expiry(1000).asSeconds()); // 1
```

You can use this undocumented feature to create a new expiry with your `seconds` argument:

``` javascript
var
  seconds = 15;

console.log(expiry(seconds * 1000).asSeconds()); // 15
```

Does it make sense?

**Comment by BigFunger** [comment]
Thanks for the suggestion. However, I don't think that gets me any closer to what I was asking for. :)
While a number passed into expiry is interpreted as milliseconds as you suggest...

```
var  expiry = require('expiry-js');
console.log(expiry(1000).asMilliseconds()); // 1000
```

Doing the same thing with a number as a string does not:

```
var  expiry = require('expiry-js');
console.log(expiry('1000').asMilliseconds()); // 0
```

I am using expiry to interpret a user-provided string and convert that into a usable length of time. Per your suggestion, I would have to do my own parsing of the string into a number before expiry gives me the desired result. This defeats the purpose of using expiry. :)

**Comment by adriano-di-giovanni** [comment]
Let me check ;)

**Comment by adriano-di-giovanni** [comment]
I've implemented requested feature.

``` javascript
var
  expiry = require('expiry-js');

console.log(expiry('2', 's').asMilliseconds()); // 2000
```

Thanks for your suggestion ;)
